# Generated by Django 4.2.3 on 2023-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_status_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
